name: sample
services:
  scraper:
    build:
      context: .
    ports:
      - "8000:8000"
    stop_grace_period: 1s
    # healthcheck:
    #   test: curl --fail http://localhost:8000/health || exit 1
    #   interval: 1m
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s
